<?php
declare(strict_types=1);
require_once __DIR__ . '/SecurityService.php';
final class CryptoService {
 public function __construct(private PDO $db){}
 public function assets():array{return $this->db->query('SELECT * FROM crypto_assets WHERE active=1 ORDER BY FIELD(symbol,"BTC","ETH","USDT","USDC","XRP")')->fetchAll();}
 public function ensureWallets(int $userId):void{$s=$this->db->query('SELECT id,symbol FROM crypto_assets WHERE active=1');foreach($s->fetchAll() as $a){$q=$this->db->prepare('SELECT id FROM crypto_wallets WHERE user_id=? AND asset_id=?');$q->execute([$userId,$a['id']]);if(!$q->fetchColumn()){$address='cs'.strtolower($a['symbol']).'_'.$userId.'_'.bin2hex(random_bytes(12));$this->db->prepare('INSERT INTO crypto_wallets(user_id,asset_id,address,balance) VALUES(?,?,?,0)')->execute([$userId,$a['id'],$address]);}}}
 public function wallets(int $userId):array{$this->ensureWallets($userId);$s=$this->db->prepare('SELECT w.*,a.symbol,a.name,a.decimals,a.usd_rate FROM crypto_wallets w JOIN crypto_assets a ON a.id=w.asset_id WHERE w.user_id=? AND a.active=1 ORDER BY FIELD(a.symbol,"BTC","ETH","USDT","USDC","XRP")');$s->execute([$userId]);return $s->fetchAll();}
 public function wallet(int $userId,string $symbol):array{$this->ensureWallets($userId);$s=$this->db->prepare('SELECT w.*,a.symbol,a.name,a.decimals,a.usd_rate FROM crypto_wallets w JOIN crypto_assets a ON a.id=w.asset_id WHERE w.user_id=? AND a.symbol=? LIMIT 1');$s->execute([$userId,strtoupper($symbol)]);$w=$s->fetch();if(!$w)throw new RuntimeException('Crypto wallet not found.');return $w;}
 public function receiveDemo(int $userId,string $symbol,string $amount):string{$amount=$this->amount($amount);$w=$this->wallet($userId,$symbol);$this->db->beginTransaction();try{$ref=$this->ref('CRX-DEP');$this->db->prepare('UPDATE crypto_wallets SET balance=balance+? WHERE id=?')->execute([$amount,$w['id']]);$this->db->prepare('INSERT INTO crypto_transactions(reference,user_id,asset_id,type,status,amount,to_address,description,completed_at) VALUES(?,?,?,"receive","completed",?,?,?,NOW())')->execute([$ref,$userId,$w['asset_id'],$amount,$w['address'],'Simulated crypto receive']);$this->db->commit();return $ref;}catch(Throwable $e){if($this->db->inTransaction())$this->db->rollBack();throw $e;}}
 public function send(int $userId,string $symbol,string $amount,string $toAddress,string $pin):string{$amount=$this->amount($amount);$toAddress=trim($toAddress);if(strlen($toAddress)<10||strlen($toAddress)>128)throw new InvalidArgumentException('Invalid destination crypto address.');(new SecurityService($this->db))->verifyTransactionPin($userId,$pin);$w=$this->wallet($userId,$symbol);if($w['status']!=='active')throw new RuntimeException('Wallet is frozen.');$this->db->beginTransaction();try{$ref=$this->ref('CRX-SND');$this->db->prepare('UPDATE crypto_wallets SET balance=balance-? WHERE id=? AND balance>=?')->execute([$amount,$w['id'],$amount]);if($this->db->rowCount()!==1)throw new RuntimeException('Insufficient crypto balance.');$this->db->prepare('INSERT INTO crypto_transactions(reference,user_id,asset_id,type,status,amount,to_address,description,completed_at) VALUES(?,?,?,"send","completed",?,?,?,NOW())')->execute([$ref,$userId,$w['asset_id'],$amount,$toAddress,'Simulated crypto send']);$this->db->commit();return $ref;}catch(Throwable $e){if($this->db->inTransaction())$this->db->rollBack();throw $e;}}
 public function convert(int $userId,string $from,string $to,string $amount,string $pin):array{$amount=$this->amount($amount);$from=strtoupper($from);$to=strtoupper($to);if($from===$to)throw new InvalidArgumentException('Choose different cryptocurrencies.');(new SecurityService($this->db))->verifyTransactionPin($userId,$pin);$fw=$this->wallet($userId,$from);$tw=$this->wallet($userId,$to);$this->db->beginTransaction();try{$stmt=$this->db->prepare('SELECT balance FROM crypto_wallets WHERE id=? FOR UPDATE');$stmt->execute([$fw['id']]);$balance=(float)$stmt->fetchColumn();if($balance<(float)$amount)throw new RuntimeException('Insufficient crypto balance.');$rate=(float)$fw['usd_rate']/(float)$tw['usd_rate'];$out=round((float)$amount*$rate,(int)$tw['decimals']);$ref=$this->ref('CRX-CNV');$this->db->prepare('UPDATE crypto_wallets SET balance=balance-? WHERE id=?')->execute([$amount,$fw['id']]);$this->db->prepare('UPDATE crypto_wallets SET balance=balance+? WHERE id=?')->execute([$out,$tw['id']]);$this->db->prepare('INSERT INTO crypto_transactions(reference,user_id,asset_id,type,status,amount,counter_asset_id,counter_amount,description,completed_at) VALUES(?,?,?,"convert","completed",?,?,?,?,?,NOW())')->execute([$ref,$userId,$fw['asset_id'],$amount,$tw['asset_id'],$out,"Converted $from to $to"]);$this->db->commit();return ['reference'=>$ref,'amount'=>$out,'symbol'=>$to];}catch(Throwable $e){if($this->db->inTransaction())$this->db->rollBack();throw $e;}}
 public function history(int $userId,int $limit=50):array{$limit=max(1,min(100,$limit));$s=$this->db->prepare('SELECT t.*,a.symbol,ca.symbol counter_symbol FROM crypto_transactions t JOIN crypto_assets a ON a.id=t.asset_id LEFT JOIN crypto_assets ca ON ca.id=t.counter_asset_id WHERE t.user_id=? ORDER BY t.id DESC LIMIT '.$limit);$s->execute([$userId]);return $s->fetchAll();}
 private function amount(string $v):string{$v=trim($v);if(!preg_match('/^\d+(\.\d{1,18})?$/',$v)||!is_finite((float)$v)||(float)$v<=0)throw new InvalidArgumentException('Invalid crypto amount.');return $v;}
 private function ref(string $prefix):string{return $prefix.'-'.date('YmdHis').'-'.strtoupper(bin2hex(random_bytes(4)));}
}
