<?php
declare(strict_types=1);
final class ReportingService{
 public function __construct(private PDO $db){}
 private function scalar(string $sql){return $this->db->query($sql)->fetchColumn();}
 public function overview():array{return ['customers'=>(int)$this->scalar("SELECT COUNT(*) FROM users WHERE role_id=(SELECT id FROM roles WHERE name='customer')"),'accounts'=>(int)$this->scalar("SELECT COUNT(*) FROM accounts"),'balance'=>(float)$this->scalar("SELECT COALESCE(SUM(available_balance),0) FROM accounts"),'transactions'=>(int)$this->scalar("SELECT COUNT(*) FROM transactions"),'completed_volume'=>(float)$this->scalar("SELECT COALESCE(SUM(amount),0) FROM transactions WHERE status='completed'"),'failed_transactions'=>(int)$this->scalar("SELECT COUNT(*) FROM transactions WHERE status='failed'"),'pending_transactions'=>(int)$this->scalar("SELECT COUNT(*) FROM transactions WHERE status IN ('pending','processing')"),'risk_open'=>(int)$this->scalar("SELECT COUNT(*) FROM risk_alerts WHERE status='open'"),'kyc_pending'=>(int)$this->scalar("SELECT COUNT(*) FROM customer_kyc WHERE status IN ('pending','requires_review')")];}
 public function daily(int $days=30):array{$days=max(7,min(365,$days));$s=$this->db->query("SELECT DATE(created_at) day,COUNT(*) transactions,COALESCE(SUM(CASE WHEN status='completed' THEN amount ELSE 0 END),0) volume,COALESCE(SUM(CASE WHEN status='completed' THEN 1 ELSE 0 END),0) completed,COALESCE(SUM(CASE WHEN status='failed' THEN 1 ELSE 0 END),0) failed FROM transactions WHERE created_at>=DATE_SUB(CURRENT_DATE,INTERVAL ".$days." DAY) GROUP BY DATE(created_at) ORDER BY day");return $s->fetchAll();}
 public function transactionTypes(int $days=30):array{$days=max(7,min(365,$days));return $this->db->query("SELECT type,COUNT(*) count,COALESCE(SUM(CASE WHEN status='completed' THEN amount ELSE 0 END),0) volume FROM transactions WHERE created_at>=DATE_SUB(CURRENT_DATE,INTERVAL ".$days." DAY) GROUP BY type ORDER BY volume DESC")->fetchAll();}
 public function customerSegments():array{return $this->db->query("SELECT CASE WHEN COALESCE(a.bal,0)=0 THEN 'Zero balance' WHEN a.bal<100000 THEN 'Below $100k' WHEN a.bal<1000000 THEN '$100k–$1m' ELSE '$1m+' END segment,COUNT(*) customers,COALESCE(SUM(a.bal),0) balance FROM users u LEFT JOIN (SELECT user_id,SUM(available_balance) bal FROM accounts GROUP BY user_id) a ON a.user_id=u.id WHERE u.role_id=(SELECT id FROM roles WHERE name='customer') GROUP BY segment ORDER BY balance DESC")->fetchAll();}
 public function topCustomers(int $days=30,int $limit=10):array{$days=max(7,min(365,$days));$limit=max(5,min(50,$limit));$s=$this->db->query("SELECT u.id,CONCAT(u.first_name,' ',u.last_name) customer,COUNT(t.id) transactions,COALESCE(SUM(CASE WHEN t.status='completed' THEN t.amount ELSE 0 END),0) volume FROM users u JOIN transactions t ON t.initiated_by=u.id WHERE u.role_id=(SELECT id FROM roles WHERE name='customer') AND t.created_at>=DATE_SUB(CURRENT_DATE,INTERVAL ".$days." DAY) GROUP BY u.id,customer ORDER BY volume DESC LIMIT ".$limit);return $s->fetchAll();}
 public function channelTypes(int $days=30):array{return $this->transactionTypes($days);}
 public function exportDailyCSV(array $rows):string{$h=fopen('php://temp','r+');fputcsv($h,['Date','Transactions','Completed','Failed','Completed Volume']);foreach($rows as $r)fputcsv($h,[$r['day'],$r['transactions'],$r['completed'],$r['failed'],number_format((float)$r['volume'],2,'.','')]);rewind($h);$x=stream_get_contents($h);fclose($h);return $x;}
 public function logExport(?int $user,string $type,array $filters,string $format):void{$this->db->prepare('INSERT INTO report_exports(user_id,report_type,filters,format) VALUES(?,?,?,?)')->execute([$user,$type,json_encode($filters),$format]);}
}