<?php

declare(strict_types=1);

final class ScheduledPaymentService
{
    public function __construct(private PDO $db) {}

    public function list(int $userId):array{$s=$this->db->prepare('SELECT sp.*,a.account_number, b.name beneficiary_name,b.account_number beneficiary_account, bl.name biller_name FROM scheduled_payments sp JOIN accounts a ON a.id=sp.from_account_id LEFT JOIN beneficiaries b ON b.id=sp.beneficiary_id LEFT JOIN billers bl ON bl.id=sp.biller_id WHERE sp.user_id=? ORDER BY sp.next_run_at');$s->execute([$userId]);return $s->fetchAll();}

    public function create(int $userId,int $fromAccountId,?int $beneficiaryId,?int $billerId,string $amount,string $currency,string $frequency,string $nextRun,string $description=''):int{
        if(($beneficiaryId===null)==($billerId===null))throw new InvalidArgumentException('Choose exactly one beneficiary or biller.');
        if(!preg_match('/^\d+(\.\d{1,4})?$/',$amount)||(float)$amount<=0)throw new InvalidArgumentException('Invalid amount.');
        if(!in_array($frequency,['once','daily','weekly','monthly'],true))throw new InvalidArgumentException('Invalid frequency.');
        $dt=date_create($nextRun);if(!$dt)throw new InvalidArgumentException('Invalid next run date.');
        $s=$this->db->prepare('SELECT * FROM accounts WHERE id=? AND user_id=? AND status="active"');$s->execute([$fromAccountId,$userId]);$account=$s->fetch();if(!$account)throw new RuntimeException('Source account not found.');
        $currency= strtoupper($currency);$s=$this->db->prepare('SELECT currency FROM account_types WHERE id=?');$s->execute([$account['account_type_id']]);if((string)$s->fetchColumn()!==$currency)throw new RuntimeException('Currency mismatch.');
        if($beneficiaryId!==null){$s=$this->db->prepare('SELECT id FROM beneficiaries WHERE id=? AND user_id=? AND status="active"');$s->execute([$beneficiaryId,$userId]);if(!$s->fetchColumn())throw new RuntimeException('Beneficiary not found or disabled.');}
        if($billerId!==null){$s=$this->db->prepare('SELECT id FROM billers WHERE id=? AND status="active"');$s->execute([$billerId]);if(!$s->fetchColumn())throw new RuntimeException('Biller not found or inactive.');}
        $s=$this->db->prepare('INSERT INTO scheduled_payments(user_id,from_account_id,beneficiary_id,biller_id,amount,currency,frequency,next_run_at,status,description) VALUES(?,?,?,?,?,?,?,?,"active",?)');$s->execute([$userId,$fromAccountId,$beneficiaryId,$billerId,$amount,$currency,$frequency,$dt->format('Y-m-d H:i:s'),trim($description)?:null]);return (int)$this->db->lastInsertId();
    }

    public function updateStatus(int $id,int $userId,string $status):void{if(!in_array($status,['active','paused','cancelled'],true))throw new InvalidArgumentException('Invalid status.');$s=$this->db->prepare('UPDATE scheduled_payments SET status=? WHERE id=? AND user_id=? AND status<>"completed"');$s->execute([$status,$id,$userId]);if(!$s->rowCount())throw new RuntimeException('Scheduled payment not found.');}

    public function runDue(int $limit=50):array{$limit=max(1,min(200,$limit));$s=$this->db->query('SELECT * FROM scheduled_payments WHERE status="active" AND next_run_at<=NOW() ORDER BY next_run_at,id LIMIT '.$limit);$rows=$s->fetchAll();$results=[];foreach($rows as $row){try{$ref=$row['biller_id']!==null?$this->executeBill((int)$row['id']):$this->executeTransfer((int)$row['id']);$this->advance((int)$row['id'],$row['frequency']);$results[]=['id'=>$row['id'],'status'=>'completed','reference'=>$ref];}catch(Throwable $e){$this->db->prepare('UPDATE scheduled_payments SET status="paused" WHERE id=?')->execute([(int)$row['id']]);$results[]=['id'=>$row['id'],'status'=>'failed','error'=>$e->getMessage()];}}return $results;}

    private function executeBill(int $id):string{$this->db->beginTransaction();try{$s=$this->db->prepare('SELECT sp.*,b.name biller_name FROM scheduled_payments sp JOIN billers b ON b.id=sp.biller_id WHERE sp.id=? FOR UPDATE');$s->execute([$id]);$r=$s->fetch();if(!$r||$r['status']!=='active')throw new RuntimeException('Schedule unavailable.');$a=$this->lockAccount((int)$r['from_account_id']);if((float)$a['available_balance']<(float)$r['amount'])throw new RuntimeException('Insufficient funds.');$ref='SCH-BILL-'.date('YmdHis').'-'.strtoupper(bin2hex(random_bytes(3)));$s=$this->db->prepare('INSERT INTO transactions(reference,type,status,amount,currency,description,initiated_by) VALUES(?,"bill_payment","processing",?,?,?,?)');$s->execute([$ref,$r['amount'],$r['currency'],'Scheduled '.$r['biller_name'].' payment #'.$id,$r['user_id']]);$tx=(int)$this->db->lastInsertId();$this->db->prepare('INSERT INTO ledger_entries(transaction_id,account_id,entry_type,amount) VALUES(?,?,"debit",?)')->execute([$tx,$a['id'],$r['amount']]);$this->db->prepare('UPDATE transactions SET status="completed",completed_at=CURRENT_TIMESTAMP WHERE id=?')->execute([$tx]);$this->db->prepare('UPDATE accounts SET available_balance=? WHERE id=?')->execute([$this->balance((int)$a['id']),$a['id']]);$this->db->commit();return $ref;}catch(Throwable $e){if($this->db->inTransaction())$this->db->rollBack();throw $e;}}

    private function executeTransfer(int $id):string{$this->db->beginTransaction();try{$s=$this->db->prepare('SELECT sp.*,b.account_number beneficiary_account FROM scheduled_payments sp JOIN beneficiaries b ON b.id=sp.beneficiary_id WHERE sp.id=? FOR UPDATE');$s->execute([$id]);$r=$s->fetch();if(!$r||$r['status']!=='active'||$r['beneficiary_account']===null)throw new RuntimeException('Schedule unavailable.');$s=$this->db->prepare('SELECT a.*,at.currency FROM accounts a JOIN account_types at ON at.id=a.account_type_id WHERE a.user_id=? AND a.status="active" AND a.account_number=?');$s->execute([$r['user_id'],$r['beneficiary_account']]);$to=$s->fetch();if(!$to)throw new RuntimeException('Beneficiary account is unavailable.');$from=$this->lockAccount((int)$r['from_account_id']);if($from['currency']!==$r['currency']||$to['currency']!==$r['currency'])throw new RuntimeException('Currency mismatch.');if((float)$from['available_balance']<(float)$r['amount'])throw new RuntimeException('Insufficient funds.');$ref='SCH-TXN-'.date('YmdHis').'-'.strtoupper(bin2hex(random_bytes(3)));$s=$this->db->prepare('INSERT INTO transactions(reference,type,status,amount,currency,description,initiated_by) VALUES(?,"transfer","processing",?,?,?,?)');$s->execute([$ref,$r['amount'],$r['currency'],'Scheduled transfer #'.$id,$r['user_id']]);$tx=(int)$this->db->lastInsertId();$this->db->prepare('INSERT INTO ledger_entries(transaction_id,account_id,entry_type,amount) VALUES(?,?,"debit",?),(?,?,"credit",?)')->execute([$tx,$from['id'],$r['amount'],$tx,$to['id'],$r['amount']]);$this->db->prepare('UPDATE transactions SET status="completed",completed_at=CURRENT_TIMESTAMP WHERE id=?')->execute([$tx]);$this->recalculate((int)$from['id']);$this->recalculate((int)$to['id']);$this->db->commit();return $ref;}catch(Throwable $e){if($this->db->inTransaction())$this->db->rollBack();throw $e;}}

    private function advance(int $id,string $frequency):void{$next=null;if($frequency==='once'){$this->db->prepare('UPDATE scheduled_payments SET status="completed",updated_at=CURRENT_TIMESTAMP WHERE id=?')->execute([$id]);return;}switch($frequency){case'daily':$next='DATE_ADD(next_run_at,INTERVAL 1 DAY)';break;case'weekly':$next='DATE_ADD(next_run_at,INTERVAL 1 WEEK)';break;case'monthly':$next='DATE_ADD(next_run_at,INTERVAL 1 MONTH)';break;} $this->db->exec('UPDATE scheduled_payments SET next_run_at='.$next.',updated_at=CURRENT_TIMESTAMP WHERE id='.(int)$id);}
    private function lockAccount(int $id):array{$s=$this->db->prepare('SELECT a.*,at.currency FROM accounts a JOIN account_types at ON at.id=a.account_type_id WHERE a.id=? FOR UPDATE');$s->execute([$id]);$r=$s->fetch();if(!$r)throw new RuntimeException('Account not found.');return $r;}
    private function balance(int $id):string{$s=$this->db->prepare('SELECT COALESCE(SUM(CASE WHEN le.entry_type="credit" THEN le.amount ELSE -le.amount END),0) FROM ledger_entries le JOIN transactions t ON t.id=le.transaction_id WHERE le.account_id=? AND t.status="completed"');$s->execute([$id]);return number_format((float)$s->fetchColumn(),4,'.','');}
    private function recalculate(int $id):void{$this->db->prepare('UPDATE accounts SET available_balance=? WHERE id=?')->execute([$this->balance($id),$id]);}
}
