<?php

declare(strict_types=1);

final class ScheduledPaymentService
{
    public function __construct(private PDO $db) {}
    public function list(int $userId):array{$s=$this->db->prepare('SELECT sp.*,a.account_number,b.name beneficiary_name,b.account_number beneficiary_account,bl.name biller_name FROM scheduled_payments sp JOIN accounts a ON a.id=sp.from_account_id LEFT JOIN beneficiaries b ON b.id=sp.beneficiary_id LEFT JOIN billers bl ON bl.id=sp.biller_id WHERE sp.user_id=? ORDER BY sp.next_run_at');$s->execute([$userId]);return $s->fetchAll();}
    public function create(int $userId,int $fromAccountId,?int $beneficiaryId,?int $billerId,string $amount,string $currency,string $frequency,string $nextRun,string $description=''):int{if(($beneficiaryId===null)==($billerId===null))throw new InvalidArgumentException('Choose exactly one beneficiary or biller.');if(!preg_match('/^\d+(\.\d{1,4})?$/',$amount)||(float)$amount<=0)throw new InvalidArgumentException('Invalid amount.');if(!in_array($frequency,['once','daily','weekly','monthly'],true))throw new InvalidArgumentException('Invalid frequency.');$dt=date_create($nextRun);if(!$dt)throw new InvalidArgumentException('Invalid next run date.');$s=$this->db->prepare('SELECT * FROM accounts WHERE id=? AND user_id=? AND status="active"');$s->execute([$fromAccountId,$userId]);$account=$s->fetch();if(!$account)throw new RuntimeException('Source account not found.');$currency=strtoupper($currency);$s=$this->db->prepare('SELECT currency FROM account_types WHERE id=?');$s->execute([$account['account_type_id']]);if((string)$s->fetchColumn()!==$currency)throw new RuntimeException('Currency mismatch.');if($beneficiaryId!==null){$s=$this->db->prepare('SELECT id FROM beneficiaries WHERE id=? AND user_id=? AND status="active"');$s->execute([$beneficiaryId,$userId]);if(!$s->fetchColumn())throw new RuntimeException('Beneficiary not found or disabled.');}if($billerId!==null){$s=$this->db->prepare('SELECT id FROM billers WHERE id=? AND status="active"');$s->execute([$billerId]);if(!$s->fetchColumn())throw new RuntimeException('Biller not found or inactive.');}$s=$this->db->prepare('INSERT INTO scheduled_payments(user_id,from_account_id,beneficiary_id,biller_id,amount,currency,frequency,next_run_at,status,description) VALUES(?,?,?,?,?,?,?,?,"active",?)');$s->execute([$userId,$fromAccountId,$beneficiaryId,$billerId,$amount,$currency,$frequency,$dt->format('Y-m-d H:i:s'),trim($description)?:null]);return (int)$this->db->lastInsertId();}
    public function updateStatus(int $id,int $userId,string $status):void{if(!in_array($status,['active','paused','cancelled'],true))throw new InvalidArgumentException('Invalid status.');$s=$this->db->prepare('UPDATE scheduled_payments SET status=? WHERE id=? AND user_id=? AND status<>"completed"');$s->execute([$status,$id,$userId]);if(!$s->rowCount())throw new RuntimeException('Scheduled payment not found.');}
    public function runDue(int $limit=50):array{$limit=max(1,min(200,$limit));$s=$this->db->query('SELECT id FROM scheduled_payments WHERE status="active" AND next_run_at<=NOW() ORDER BY next_run_at,id LIMIT '.$limit);$ids=$s->fetchAll(PDO::FETCH_COLUMN);$results=[];foreach($ids as $id){$claim=$this->db->prepare('UPDATE scheduled_payments SET status="processing",last_run_at=NOW(),last_error=NULL WHERE id=? AND status="active" AND next_run_at<=NOW()');$claim->execute([(int)$id]);if(!$claim->rowCount())continue;try{$s=$this->db->prepare('SELECT biller_id,frequency FROM scheduled_payments WHERE id=?');$s->execute([(int)$id]);$row=$s->fetch();$ref=$row['biller_id']!==null?$this->executeBill((int)$id):$this->executeTransfer((int)$id);$this->advance((int)$id,$row['frequency']);$results[]=['id'=>$id,'status'=>'completed','reference'=>$ref];}catch(Throwable $e){$this->db->prepare('UPDATE scheduled_payments SET status="paused",last_error=? WHERE id=?')->execute([substr($e->getMessage(),0,500),(int)$id]);$results[]=['id'=>$id,'status'=>'failed','error'=>$e->getMessage()];}}return $results;}
    private function executeBill(int $id):string{$this->db->beginTransaction();try{$s=$this->db->prepare('SELECT sp.*,b.name biller_name FROM scheduled_payments sp JOIN billers b ON b.id=sp.biller_id WHERE sp.id=? FOR UPDATE');$s->execute([$id]);$r=$s->fetch();if(!$r||$r['status']!=='processing')throw new RuntimeException('Schedule unavailable.');$a=$this->lockAccount((int)$r['from_account_id']);if($a['currency']!==$r['currency'])throw new RuntimeException('Currency mismatch.');if((float)$a['available_balance']<(float)$r['amount'])throw new RuntimeException('Insufficient funds.');$ref='SCH-BILL-'.date('YmdHis').'-'.strtoupper(bin2hex(random_bytes(3)));$s=$this->db->prepare('INSERT INTO transactions(reference,type,status,amount,currency,description,initiated_by) VALUES(?,"bill_payment","processing",?,?,?,?)');$s->execute([$ref,$r['amount'],$r['currency'],'Scheduled '.$r['biller_name'].' payment #'.$id,$r['user_id']]);$tx=(int)$this->db->lastInsertId();$this->db->prepare('INSERT INTO bill_payments(user_id,account_id,biller_id,transaction_id,customer_reference,provider_reference,amount,currency,status) VALUES(?,?,?,?,?,?,?,?,"completed")')->execute([$r['user_id'],$a['id'],$r['biller_id'],$tx,'SCHEDULE-'.$id,$ref,$r['amount'],$r['currency']]);$this->db->prepare('INSERT INTO ledger_entries(transaction_id,account_id,entry_type,amount) VALUES(?,?,"debit",?)')->execute([$tx,$a['id'],$r['amount']]);$this->db->prepare('UPDATE transactions SET status="completed",completed_at=CURRENT_TIMESTAMP WHERE id=?')->execute([$tx]);$this->db->prepare('UPDATE accounts SET available_balance=? WHERE id=?')->execute([$this->balance((int)$a['id']),$a['id']]);$this->db->commit();return $ref;}catch(Throwable $e){if($this->db->inTransaction())$this->db->rollBack();throw $e;}}
    private function executeTransfer(int $id):string{$this->db->beginTransaction();try{$s=$this->db->prepare('SELECT sp.*,b.account_number beneficiary_account,b.status beneficiary_status FROM scheduled_payments sp JOIN beneficiaries b ON b.id=sp.beneficiary_id WHERE sp.id=? FOR UPDATE');$s->execute([$id]);$r=$s->fetch();if(!$r||$r['status']!=='processing'||$r['beneficiary_status']!=='active')throw new RuntimeException('Schedule or beneficiary unavailable.');$s=$this->db->prepare('SELECT a.*,at.currency FROM accounts a JOIN account_types at ON at.id=a.account_type_id WHERE a.status="active" AND a.account_number=?');$s->execute([$r['beneficiary_account']]);$to=$s->fetch();if(!$to)throw new RuntimeException('Beneficiary account is unavailable.');$sourceId=(int)$r['from_account_id'];$destId=(int)$to['id'];if($sourceId===$destId)throw new RuntimeException('Source and destination must differ.');$ids=[$sourceId,$destId];sort($ids,SORT_NUMERIC);$locked=[];foreach($ids as $accountId)$locked[$accountId]=$this->lockAccount($accountId);$from=$locked[$sourceId];$to=$locked[$destId];if($from['currency']!==$r['currency']||$to['currency']!==$r['currency'])throw new RuntimeException('Currency mismatch.');if((float)$from['available_balance']<(float)$r['amount'])throw new RuntimeException('Insufficient funds.');$ref='SCH-TXN-'.date('YmdHis').'-'.strtoupper(bin2hex(random_bytes(3)));$s=$this->db->prepare('INSERT INTO transactions(reference,type,status,amount,currency,description,initiated_by) VALUES(?,"transfer","processing",?,?,?,?)');$s->execute([$ref,$r['amount'],$r['currency'],'Scheduled transfer #'.$id,$r['user_id']]);$tx=(int)$this->db->lastInsertId();$this->db->prepare('INSERT INTO ledger_entries(transaction_id,account_id,entry_type,amount) VALUES(?,?,"debit",?),(?,?,"credit",?)')->execute([$tx,$from['id'],$r['amount'],$tx,$to['id'],$r['amount']]);$this->db->prepare('UPDATE transactions SET status="completed",completed_at=CURRENT_TIMESTAMP WHERE id=?')->execute([$tx]);$this->recalculate((int)$from['id']);$this->recalculate((int)$to['id']);$this->db->commit();return $ref;}catch(Throwable $e){if($this->db->inTransaction())$this->db->rollBack();throw $e;}}
    private function advance(int $id,string $frequency):void{if($frequency==='once'){$this->db->prepare('UPDATE scheduled_payments SET status="completed",updated_at=CURRENT_TIMESTAMP WHERE id=?')->execute([$id]);return;}$next=$frequency==='daily'?'DATE_ADD(next_run_at,INTERVAL 1 DAY)':($frequency==='weekly'?'DATE_ADD(next_run_at,INTERVAL 1 WEEK)':'DATE_ADD(next_run_at,INTERVAL 1 MONTH)');$this->db->exec('UPDATE scheduled_payments SET status="active",next_run_at='.$next.',updated_at=CURRENT_TIMESTAMP WHERE id='.(int)$id);}
    private function lockAccount(int $id):array{$s=$this->db->prepare('SELECT a.*,at.currency FROM accounts a JOIN account_types at ON at.id=a.account_type_id WHERE a.id=? FOR UPDATE');$s->execute([$id]);$r=$s->fetch();if(!$r)throw new RuntimeException('Account not found.');if($r['status']!=='active')throw new RuntimeException('Account is not active.');return $r;}
    private function balance(int $id):string{$s=$this->db->prepare('SELECT COALESCE(SUM(CASE WHEN le.entry_type="credit" THEN le.amount ELSE -le.amount END),0) FROM ledger_entries le JOIN transactions t ON t.id=le.transaction_id WHERE le.account_id=? AND t.status="completed"');$s->execute([$id]);return number_format((float)$s->fetchColumn(),4,'.','');}
    private function recalculate(int $id):void{$this->db->prepare('UPDATE accounts SET available_balance=? WHERE id=?')->execute([$this->balance($id),$id]);}
}
