<?php
declare(strict_types=1);
final class SecurityService
{
 public function __construct(private PDO $db){}
 public function setTransactionPin(int $userId,string $pin):void{$this->validatePin($pin);$this->db->prepare('UPDATE users SET transaction_pin_hash=? WHERE id=?')->execute([password_hash($pin,PASSWORD_DEFAULT),$userId]);$this->event($userId,'transaction_pin_changed','warning',null,null);}
 public function verifyTransactionPin(int $userId,string $pin):void{$s=$this->db->prepare('SELECT transaction_pin_hash FROM users WHERE id=?');$s->execute([$userId]);$h=$s->fetchColumn();if(!$h||!password_verify($pin,(string)$h))throw new RuntimeException('Invalid transaction PIN.');}
 public function assertTransferAllowed(int $userId,string $amount,string $currency='NGN'):void{if(!preg_match('/^\d+(\.\d{1,4})?$/',$amount)||(float)$amount<=0)throw new InvalidArgumentException('Invalid transfer amount.');$s=$this->db->prepare('SELECT per_transaction_limit,daily_limit FROM transfer_limits WHERE (user_id=? OR user_id IS NULL) AND currency=? ORDER BY user_id IS NULL ASC LIMIT 1');$s->execute([$userId,$currency]);$l=$s->fetch()?:['per_transaction_limit'=>1000000,'daily_limit'=>5000000];if((float)$amount>(float)$l['per_transaction_limit'])throw new RuntimeException('Transfer exceeds the per-transaction limit.');$s=$this->db->prepare('SELECT COALESCE(SUM(amount),0) FROM transactions WHERE initiated_by=? AND type="transfer" AND status IN ("processing","completed") AND currency=? AND created_at>=CURRENT_DATE');$s->execute([$userId,$currency]);if((float)$s->fetchColumn()+(float)$amount>(float)$l['daily_limit'])throw new RuntimeException('Transfer exceeds the daily limit.');}
 public function assertIdempotency(string $key):?string{if(!preg_match('/^[A-Za-z0-9._:-]{8,100}$/',$key))throw new InvalidArgumentException('Invalid idempotency key.');$s=$this->db->prepare('SELECT reference FROM transactions WHERE idempotency_key=?');$s->execute([$key]);$r=$s->fetchColumn();return $r?:null;}
 public function loginBlocked(string $email,?string $ip=null):bool{$s=$this->db->prepare('SELECT locked_until FROM users WHERE email=?');$s->execute([$email]);$until=$s->fetchColumn();if($until&&strtotime((string)$until)>time())return true;$s=$this->db->prepare('SELECT COUNT(*) FROM login_attempts WHERE success=0 AND created_at>=DATE_SUB(NOW(),INTERVAL 15 MINUTE) AND (email=? OR ip_address=?)');$s->execute([$email,$ip]);return (int)$s->fetchColumn()>=8;}
 public function recordLoginFailure(string $email,?string $ip):void{$this->db->prepare('INSERT INTO login_attempts(email,ip_address,success) VALUES(?,?,0)')->execute([$email,$ip]);$s=$this->db->prepare('SELECT COUNT(*) FROM login_attempts WHERE email=? AND success=0 AND created_at>=DATE_SUB(NOW(),INTERVAL 15 MINUTE)');$s->execute([$email]);if((int)$s->fetchColumn()>=8){$this->db->prepare('UPDATE users SET locked_until=DATE_ADD(NOW(),INTERVAL 15 MINUTE) WHERE email=?')->execute([$email]);}}
 public function recordLoginSuccess(int $userId,string $email,?string $ip,?string $ua):void{$this->db->prepare('UPDATE users SET locked_until=NULL WHERE id=?')->execute([$userId]);$this->event($userId,'login_success','info',$ip,$ua);}
 public function changePassword(int $userId,string $current,string $new):void{$s=$this->db->prepare('SELECT password_hash FROM users WHERE id=?');$s->execute([$userId]);$hash=$s->fetchColumn();if(!$hash||!password_verify($current,(string)$hash))throw new RuntimeException('Current password is incorrect.');if(strlen($new)<10||!preg_match('/[A-Z]/',$new)||!preg_match('/[a-z]/',$new)||!preg_match('/\d/',$new))throw new InvalidArgumentException('Password must be at least 10 characters and contain upper, lower and numeric characters.');if(password_verify($new,(string)$hash))throw new InvalidArgumentException('New password must differ from the current password.');$this->db->prepare('UPDATE users SET password_hash=?,password_changed_at=CURRENT_TIMESTAMP WHERE id=?')->execute([password_hash($new,PASSWORD_DEFAULT),$userId]);$this->event($userId,'password_changed','warning');}
 public function revokeSessions(int $userId):void{$this->db->prepare('DELETE FROM user_sessions WHERE user_id=?')->execute([$userId]);$this->event($userId,'sessions_revoked','warning');}
 public function event(?int $userId,string $type,string $severity='info',?string $ip=null,?string $ua=null,array $details=[]):void{$this->db->prepare('INSERT INTO security_events(user_id,event_type,severity,ip_address,user_agent,details) VALUES(?,?,?,?,?,?)')->execute([$userId,$type,$severity,$ip,$ua,$details?json_encode($details):null]);}
 public function securityEvents(int $userId,int $limit=50):array{$limit=max(1,min(100,$limit));$s=$this->db->prepare('SELECT * FROM security_events WHERE user_id=? ORDER BY created_at DESC LIMIT '.$limit);$s->execute([$userId]);return $s->fetchAll();}
 private function validatePin(string $pin):void{if(!preg_match('/^\d{4,6}$/',$pin))throw new InvalidArgumentException('Transaction PIN must be 4 to 6 digits.');}
}