<?php
require_once dirname(__DIR__) . '/app/helpers.php';
require_once dirname(__DIR__) . '/app/Services/BeneficiaryService.php';
require_once dirname(__DIR__) . '/app/Services/AccountService.php';
require_auth();
$user=auth_user();$db=Database::connection();$svc=new BeneficiaryService($db);$accountService=new AccountService($db);$error=null;$success=null;
try{if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$action=$_POST['action']??'';$id=(int)($_POST['id']??0);if($action==='add'){$svc->create((int)$user['id'],$_POST['name']??'',$_POST['account_number']??'',$_POST['bank_name']??'',$_POST['nickname']??null);$success='Beneficiary verified and added successfully.';}elseif($action==='disable'){$svc->disable((int)$user['id'],$id);$success='Beneficiary disabled.';}elseif($action==='enable'){$svc->enable((int)$user['id'],$id);$success='Beneficiary re-enabled.';}elseif($action==='delete'){$svc->delete((int)$user['id'],$id);$success='Beneficiary removed.';}}}catch(Throwable $e){$error=$e->getMessage();}
$items=$svc->list((int)$user['id']);$totalBalance=$accountService->getTotalBalance((int)$user['id']);$pageTitle='Beneficiaries';$currentPage='beneficiaries';require __DIR__.'/partials/header.php';require __DIR__.'/partials/sidebar.php';
?>
<div class="d-flex justify-content-between align-items-center mb-4"><div><h3 class="fw-bold mb-1">Beneficiaries</h3><p class="text-muted mb-0">Save verified CommServe accounts for quick transfers.</p></div><a href="<?=url('transfer.php')?>?type=beneficiary" class="btn btn-primary"><i class="bi bi-send me-2"></i>Send to Beneficiary</a></div>
<?php if($error):?><div class="alert alert-danger"><i class="bi bi-exclamation-triangle me-2"></i><?=e($error)?></div><?php endif;?><?php if($success):?><div class="alert alert-success"><i class="bi bi-check-circle me-2"></i><?=e($success)?></div><?php endif;?>
<div class="row g-4"><div class="col-lg-4"><div class="card border-0 shadow-sm"><div class="card-header bg-white fw-bold"><i class="bi bi-person-plus me-2"></i>Add Beneficiary</div><div class="card-body p-4"><form method="post" class="row g-3"><?=csrf_field()?><input type="hidden" name="action" value="add"><div class="col-12"><label class="form-label">Account Number</label><input name="account_number" class="form-control font-monospace" inputmode="numeric" pattern="\d{10}" maxlength="10" placeholder="0100000001" required><div class="form-text">Only an active 10-digit CommServe account can be added.</div></div><div class="col-12"><label class="form-label">Verified Account Holder</label><input name="name" class="form-control" placeholder="Enter the account holder name" required><div class="form-text">The server verifies the account and stores the real account-holder name.</div></div><div class="col-12"><label class="form-label">Nickname <span class="text-muted">(optional)</span></label><input name="nickname" class="form-control" maxlength="80" placeholder="e.g. Brother, Supplier"></div><div class="col-12"><label class="form-label">Bank Name</label><input name="bank_name" class="form-control" value="CommServe Demo Bank" required></div><div class="col-12"><button class="btn btn-primary w-100"><i class="bi bi-shield-check me-2"></i>Verify & Add</button></div></form><hr><div class="small text-muted"><i class="bi bi-info-circle me-1"></i>The supplied name is not trusted as proof of ownership. The active account is looked up server-side and its registered holder name is stored.</div></div></div></div>
<div class="col-lg-8"><div class="card border-0 shadow-sm"><div class="card-header bg-white d-flex justify-content-between align-items-center"><h6 class="fw-bold mb-0">Your Beneficiaries (<?=count($items)?>)</h6><span class="badge text-bg-light border">Active: <?=count(array_filter($items,fn($b)=>$b['status']==='active'))?></span></div><div class="table-responsive"><table class="table align-middle mb-0"><thead class="table-light"><tr><th>Verified Holder</th><th>Account</th><th>Nickname</th><th>Status</th><th>Added</th><th>Actions</th></tr></thead><tbody><?php if(!$items):?><tr><td colspan="6" class="text-center text-muted py-5">No beneficiaries yet.</td></tr><?php else:foreach($items as $b):?><tr><td><div class="fw-semibold"><?=e($b['name'])?></div><div class="small text-success"><i class="bi bi-patch-check-fill me-1"></i>Verified</div></td><td class="font-monospace"><?=e($b['account_number'])?><div class="small text-muted"><?=e($b['bank_name'])?></div></td><td><?=e($b['nickname']??'—')?></td><td><span class="badge <?=$b['status']==='active'?'text-bg-success':'text-bg-secondary'?>"><?=e($b['status'])?></span><?php if(($b['account_status']??'')!=='active'):?><div class="small text-danger mt-1">Account inactive</div><?php endif;?></td><td class="small text-muted"><?=e(date('M d, Y',strtotime($b['created_at'])))?></td><td><div class="d-flex gap-1 flex-wrap"><?php if($b['status']==='active'&&($b['account_status']??'')==='active'):?><a href="<?=url('transfer.php')?>?type=beneficiary&beneficiary=<?=$b['id']?>" class="btn btn-sm btn-primary">Send</a><form method="post" onsubmit="return confirm('Disable this beneficiary?')"><?=csrf_field()?><input type="hidden" name="action" value="disable"><input type="hidden" name="id" value="<?=$b['id']?>"><button class="btn btn-sm btn-outline-danger">Disable</button></form><?php elseif($b['status']==='disabled'):?><form method="post"><?=csrf_field()?><input type="hidden" name="action" value="enable"><input type="hidden" name="id" value="<?=$b['id']?>"><button class="btn btn-sm btn-outline-success">Enable</button></form><?php endif;?><form method="post" onsubmit="return confirm('Remove this beneficiary permanently? This cannot be undone.')"><?=csrf_field()?><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?=$b['id']?>"><button class="btn btn-sm btn-outline-secondary">Delete</button></form></div></td></tr><?php endforeach;endif;?></tbody></table></div></div><div class="card border-0 bg-light mt-4"><div class="card-body p-3 small text-muted"><i class="bi bi-shield-check me-2"></i>Beneficiary transfers require Transaction PIN and OTP. Create, enable, disable and delete actions are audit logged.</div></div></div></div>
<?php require __DIR__.'/partials/footer.php'; ?>
