<?php
require_once dirname(__DIR__) . '/app/helpers.php';
require_auth();
require_once dirname(__DIR__) . '/app/Services/BeneficiaryService.php';
$svc=new BeneficiaryService(Database::connection());$user=auth_user();$error=null;$success=null;
try{
 if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$action=$_POST['action']??'';if($action==='add'){$svc->create((int)$user['id'],$_POST['name']??'',$_POST['account_number']??'',$_POST['bank_name']??'');$success='Beneficiary added.';}elseif($action==='disable'){$svc->disable((int)$user['id'],(int)$_POST['id']);$success='Beneficiary disabled.';}}
}catch(Throwable $e){$error=$e->getMessage();}
$items=$svc->list((int)$user['id']);
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Beneficiaries - <?=e(APP_NAME)?></title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="/commserve/public/assets/css/app.css" rel="stylesheet"></head><body><div class="container py-4"><div class="d-flex justify-content-between align-items-center mb-4"><h2>Beneficiaries</h2><a href="/commserve/public/dashboard.php" class="btn btn-outline-secondary">Dashboard</a></div><?php if($error):?><div class="alert alert-danger"><?=e($error)?></div><?php endif;?><?php if($success):?><div class="alert alert-success"><?=e($success)?></div><?php endif;?><div class="card shadow-sm border-0 mb-4"><div class="card-body"><h5>Add beneficiary</h5><form method="post" class="row g-3"><?=csrf_field()?><input type="hidden" name="action" value="add"><div class="col-md-4"><label class="form-label">Name</label><input name="name" class="form-control" required></div><div class="col-md-4"><label class="form-label">Account number</label><input name="account_number" class="form-control" inputmode="numeric" pattern="\d{10}" maxlength="10" required></div><div class="col-md-4"><label class="form-label">Bank</label><input name="bank_name" class="form-control" value="CommServe Demo Bank" required></div><div class="col-12"><button class="btn btn-primary">Add beneficiary</button></div></form></div></div><div class="card shadow-sm border-0"><div class="card-body"><h5>Your beneficiaries</h5><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Name</th><th>Account</th><th>Bank</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($items as $b):?><tr><td><?=e($b['name'])?></td><td><?=e($b['account_number'])?></td><td><?=e($b['bank_name'])?></td><td><span class="badge text-bg-<?=($b['status']==='active'?'success':'secondary')?>"><?=e($b['status'])?></span></td><td><?php if($b['status']==='active'):?><form method="post"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="disable"><input type="hidden" name="id" value="<?=$b['id']?>"><button class="btn btn-sm btn-outline-danger">Disable</button></form><?php endif;?></td></tr><?php endforeach;?></tbody></table></div></div></div></div></body></html>
