<?php
require_once dirname(__DIR__).'/app/helpers.php';require_auth();require_once dirname(__DIR__).'/app/Services/CryptoService.php';
$svc=new CryptoService(Database::connection());$user=auth_user();$wallets=$svc->wallets((int)$user['id']);$history=$svc->history((int)$user['id']);$pageTitle='Crypto';$currentPage='crypto';require __DIR__.'/partials/header.php';require __DIR__.'/partials/sidebar.php';
?>
<div class="d-flex justify-content-between align-items-center mb-4"><div><h2 class="fw-bold mb-1">Crypto Wallet</h2><p class="text-muted mb-0">Manage simulated cryptocurrency balances, transfers and conversions.</p></div><div class="d-flex gap-2"><a class="btn btn-primary" href="<?=url('crypto-receive.php')?>"><i class="bi bi-download me-1"></i>Receive</a><a class="btn btn-outline-primary" href="<?=url('crypto-send.php')?>"><i class="bi bi-send me-1"></i>Send</a><a class="btn btn-outline-dark" href="<?=url('crypto-convert.php')?>"><i class="bi bi-arrow-left-right me-1"></i>Convert</a></div></div>
<div class="alert alert-warning"><strong>Demo only:</strong> these crypto wallets, addresses and transactions are simulated. No blockchain transaction is broadcast and no real cryptocurrency is held.</div>
<div class="row g-3 mb-4">
<?php foreach($wallets as $w):?><div class="col-md-6 col-xl-4"><div class="card border-0 shadow-sm h-100"><div class="card-body"><div class="d-flex justify-content-between"><div><span class="badge text-bg-dark"><?=e($w['symbol'])?></span> <strong><?=e($w['name'])?></strong></div><small class="text-muted">USD rate</small></div><div class="display-6 fw-bold mt-3"><?=e(rtrim(rtrim(number_format((float)$w['balance'],18,'.',''),'0'),'.'))?> <small class="fs-6"><?=e($w['symbol'])?></small></div><div class="small text-muted mt-2">≈ $<?=number_format((float)$w['balance']*(float)$w['usd_rate'],2)?></div><div class="small text-truncate mt-3" title="<?=e($w['address'])?>"><i class="bi bi-qr-code me-1"></i><?=e($w['address'])?></div></div></div></div><?php endforeach; ?>
</div>
<div class="card border-0 shadow-sm"><div class="card-header bg-white d-flex justify-content-between"><strong>Crypto activity</strong><a href="<?=url('crypto-receive.php')?>" class="btn btn-sm btn-outline-primary">Get receive address</a></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Reference</th><th>Type</th><th>Asset</th><th>Amount</th><th>Details</th><th>Date</th></tr></thead><tbody><?php if(!$history):?><tr><td colspan="6" class="text-center text-muted py-4">No crypto transactions yet.</td></tr><?php else:foreach($history as $tx):?><tr><td class="small fw-semibold"><?=e($tx['reference'])?></td><td><?=e(ucfirst($tx['type']))?></td><td><?=e($tx['symbol'])?></td><td><?=e(rtrim(rtrim(number_format((float)$tx['amount'],18,'.',''),'0'),'.'))?> <?=e($tx['symbol'])?><?php if($tx['type']==='convert'):?> → <?=e(rtrim(rtrim(number_format((float)$tx['counter_amount'],18,'.',''),'0'),'.'))?> <?=e($tx['counter_symbol'])?><?php endif;?></td><td class="small text-muted"><?=e($tx['description']??'')?></td><td class="small"><?=e(date('M d, Y H:i',strtotime($tx['created_at'])))?></td></tr><?php endforeach;endif;?></tbody></table></div></div>
<?php require __DIR__.'/partials/footer.php';?>