<?php
require_once dirname(__DIR__) . '/app/helpers.php';
$error=null;
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf(); $first=trim($_POST['first_name']??''); $last=trim($_POST['last_name']??''); $email=strtolower(trim($_POST['email']??'')); $password=(string)($_POST['password']??''); $confirm=(string)($_POST['password_confirmation']??'');
 if($first===''||$last===''||!filter_var($email,FILTER_VALIDATE_EMAIL)||strlen($password)<8||$password!==$confirm){$error=t('Enter valid details and a password of at least 8 characters.');}else{
  try{$pdo=Database::connection();$role=$pdo->query("SELECT id FROM roles WHERE name='customer'")->fetchColumn();$stmt=$pdo->prepare('INSERT INTO users(role_id,email,password_hash,first_name,last_name) VALUES(?,?,?,?,?)');$stmt->execute([$role,$email,password_hash($password,PASSWORD_DEFAULT),$first,$last]);$uid=(int)$pdo->lastInsertId();$account='01'.str_pad((string)$uid,8,'0',STR_PAD_LEFT);$type=$pdo->query("SELECT id FROM account_types WHERE name='Savings'")->fetchColumn();$s=$pdo->prepare('INSERT INTO accounts(user_id,account_type_id,account_number) VALUES(?,?,?)');$s->execute([$uid,$type,$account]);redirect(url('login.php'));}catch(PDOException $e){$error=$e->getCode()==='23000'?t('An account with that email already exists.'):t('Registration failed.');}
 }
}
?><!doctype html><html lang="<?=e(current_locale())?>"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e(t('Create account'))?></title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="<?=url('assets/css/app.css')?>" rel="stylesheet"></head><body class="auth-bg"><div class="container py-5"><div class="row justify-content-center"><div class="col-md-7 col-lg-6"><div class="card border-0 shadow-lg"><div class="card-body p-4 p-lg-5"><div class="d-flex justify-content-end mb-3"><?=language_selector('form-select form-select-sm w-auto')?></div><h3 class="fw-bold"><?=e(t('Create your account'))?></h3><p class="text-muted"><?=e(t('Open your CommServe account in minutes.'))?></p><?php if($error):?><div class="alert alert-danger"><?=e($error)?></div><?php endif;?><form method="post"><?=csrf_field()?><div class="row"><div class="col-md-6 mb-3"><label class="form-label"><?=e(t('First name'))?></label><input name="first_name" class="form-control" required></div><div class="col-md-6 mb-3"><label class="form-label"><?=e(t('Last name'))?></label><input name="last_name" class="form-control" required></div></div><div class="mb-3"><label class="form-label"><?=e(t('Email'))?></label><input type="email" name="email" class="form-control" required></div><div class="row"><div class="col-md-6 mb-3"><label class="form-label"><?=e(t('Password'))?></label><input type="password" name="password" class="form-control" minlength="8" required></div><div class="col-md-6 mb-3"><label class="form-label"><?=e(t('Confirm password'))?></label><input type="password" name="password_confirmation" class="form-control" minlength="8" required></div></div><button class="btn btn-primary w-100"><?=e(t('Create account'))?></button></form><div class="text-center mt-3"><a href="<?=url('login.php')?>"><?=e(t('Already have an account? Sign in'))?></a></div></div></div></div></div></div></body></html>
