<?php
require_once dirname(__DIR__) . '/app/helpers.php';
require_auth();
require_once dirname(__DIR__) . '/app/Services/TransactionService.php';
$svc=new TransactionService(Database::connection());$user=auth_user();$ref=trim($_GET['ref']??$_POST['reference']??'');$error=null;$success=null;$demoOtp=null;
try{
 if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$action=$_POST['action']??'';if($action==='request_otp'){$demoOtp=$svc->requestOtp($ref,(int)$user['id']);$success='Demo OTP generated. Use the code shown below.';}elseif($action==='verify_otp'){$svc->verifyOtp($ref,(int)$user['id'],$_POST['otp']??'');$success='OTP verified successfully.';}}
 $tx=$svc->findByReference($ref);if(!$tx)throw new RuntimeException('Transaction not found.');
}catch(Throwable $e){$error=$e->getMessage();$tx=$tx??null;}
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Transaction - <?=e(APP_NAME)?></title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"></head><body><div class="container py-4"><a href="/commserve/public/transactions.php" class="btn btn-link px-0">← Transactions</a><?php if($error):?><div class="alert alert-danger"><?=e($error)?></div><?php endif;?><?php if($success):?><div class="alert alert-success"><?=e($success)?></div><?php endif;?><?php if($demoOtp):?><div class="alert alert-warning"><b>Demo OTP:</b> <?=e($demoOtp)?> — in a real deployment this would be delivered through a trusted OTP channel.</div><?php endif;?><?php if($tx):?><div class="card border-0 shadow-sm"><div class="card-body"><h3><?=e($tx['type'])?></h3><p class="text-muted mb-1"><?=e($tx['reference'])?></p><h2>₦<?=number_format((float)$tx['amount'],2)?></h2><span class="badge text-bg-secondary"><?=e($tx['status'])?></span><hr><p><?=e($tx['description']??'')?></p><p class="small text-muted">Created <?=e($tx['created_at'])?></p><?php if(in_array($tx['status'],['pending','processing'],true)):?><form method="post" class="mt-4"><?=csrf_field()?><input type="hidden" name="reference" value="<?=e($ref)?>"><input type="hidden" name="action" value="request_otp"><button class="btn btn-primary">Generate demo OTP</button></form><form method="post" class="row g-2 mt-2"><?=csrf_field()?><input type="hidden" name="reference" value="<?=e($ref)?>"><input type="hidden" name="action" value="verify_otp"><div class="col-auto"><input name="otp" class="form-control" placeholder="6-digit OTP" maxlength="6" required></div><div class="col-auto"><button class="btn btn-outline-primary">Verify OTP</button></div></form><?php endif;?></div></div><?php endif;?></div></body></html>
