<?php
require_once dirname(__DIR__,2).'/app/helpers.php';require_role('admin');require_once dirname(__DIR__,2).'/app/Services/AdminOperationsService.php';require_once dirname(__DIR__,2).'/app/Services/TransferService.php';
$svc=new AdminOperationsService(Database::connection());$error=null;$success=null;
if($_SERVER['REQUEST_METHOD']==='POST'){try{verify_csrf();$id=(int)$_POST['id'];if($_POST['decision']==='approve'){$type=$svc->approveAction($id,(int)auth_user()['id'],$_POST['decision_reason']??'');$success=$type==='otp_stage_approval'?t('OTP stage approved.'):t('Action approved and executed.');}else{$svc->rejectAction($id,(int)auth_user()['id'],$_POST['decision_reason']??'');$success=t('Action rejected.');}}catch(Throwable $e){$error=$e->getMessage();}}
$rows=$svc->pendingActions();
function action_badge_class(string $type):string{return match($type){'otp_stage_approval'=>'text-bg-primary','transfer_approval'=>'text-bg-info','reversal'=>'text-bg-warning','refund'=>'text-bg-dark',default=>'text-bg-secondary'};}
?><!doctype html><html lang="<?=e(current_locale())?>"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e(t('Approvals'))?> - <?=e(APP_NAME)?></title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"></head><body><div class="container-fluid p-4"><div class="d-flex justify-content-between mb-4"><div><h2><?=e(t('Maker / Checker Approvals'))?></h2><p class="text-muted mb-0 small"><?=e(t('Every submitted transfer OTP stage (1-4) is queued here. Approving stages 1-3 unlocks the next stage for the customer; approving stage 4 releases the funds.'))?></p></div><a href="<?=url('admin/')?>"><?=e(t('Dashboard'))?></a></div><?php if($error):?><div class="alert alert-danger"><?=e($error)?></div><?php endif;?><?php if($success):?><div class="alert alert-success"><?=e($success)?></div><?php endif;?>
<div class="card border-0 shadow-sm"><div class="table-responsive"><table class="table align-middle"><thead><tr><th><?=e(t('Action'))?></th><th><?=e(t('Entity'))?></th><th><?=e(t('Requester'))?></th><th><?=e(t('Reason'))?></th><th><?=e(t('Created'))?></th><th><?=e(t('Decision'))?></th></tr></thead><tbody><?php if(!$rows):?><tr><td colspan="6" class="text-center text-muted py-4"><?=e(t('No pending approvals.'))?></td></tr><?php endif;?><?php foreach($rows as $r):$stage=(int)($r['otp_stage']??0);$label=$stage>0?TransferService::stageLabel($stage):'';?><tr>
<td><span class="badge <?=action_badge_class((string)$r['action_type'])?>"><?=e((string)$r['action_type'])?></span><?php if($r['action_type']==='otp_stage_approval'&&$stage>0):?><div class="small text-muted mt-1"><i class="bi bi-shield-lock me-1"></i><?=e(t('Stage %s of %s',null,[$stage,TransferService::OTP_STAGES]))?> — <?=e(t($label))?></div><?php elseif($r['action_type']==='transfer_approval'):?><div class="small text-muted mt-1"><?=e(t('Customer transfer release'))?></div><?php endif;?></td>
<td><?php if(!empty($r['entity_reference'])):?><a href="<?=url('admin/transaction.php')?>?reference=<?=urlencode($r['entity_reference'])?>"><?=e($r['entity_reference'])?></a><?php if(isset($r['entity_amount'])):?><div class="small text-muted"><?=format_money((float)$r['entity_amount'],(string)($r['entity_currency']??'USD'))?> · <?=e(tx_label((string)($r['entity_status']??'')))?></div><?php endif; else: ?><?=e($r['entity_type'])?> #<?=e((string)$r['entity_id'])?><?php endif; ?></td>
<td><?=e($r['requester_email'])?></td><td class="small" style="max-width:320px"><?=e($r['reason'])?></td><td class="small"><?=e($r['created_at'])?></td><td><form method="post" class="d-flex gap-2 flex-wrap"><?=csrf_field()?><input type="hidden" name="id" value="<?=$r['id']?>"><input name="decision_reason" class="form-control form-control-sm" placeholder="<?=e(t('Decision reason'))?>"><button name="decision" value="approve" class="btn btn-sm btn-success"><?=e(t('Approve'))?></button><button name="decision" value="reject" class="btn btn-sm btn-outline-danger"><?=e(t('Reject'))?></button></form></td></tr><?php endforeach;?></tbody></table></div></div></div></body></html>
