<?php
require_once dirname(__DIR__, 2) . '/app/helpers.php';
require_once dirname(__DIR__, 2) . '/app/Services/FundingService.php';
require_role('admin');
$db=Database::connection();$service=new FundingService($db);$message=null;$error=null;
if($_SERVER['REQUEST_METHOD']==='POST'){try{verify_csrf();$accountId=(int)($_POST['account_id']??0);$amount=trim((string)($_POST['amount']??''));$type=$_POST['type']??'';$description=trim((string)($_POST['description']??''));$user=auth_user();if($type==='opening_balance'){$reference=$service->openingBalance($accountId,$amount,(int)$user['id']);}elseif($type==='deposit'){$reference=$service->fund($accountId,$amount,$description?:'Account funding',(int)$user['id']);}else{throw new RuntimeException('Invalid funding operation.');}$message=t('Ledger-backed funding completed. Reference:').' '.$reference;}catch(Throwable $e){$error=$e->getMessage();}}
$accounts=$db->query('SELECT a.id,a.account_number,a.available_balance,at.name AS type,at.currency,u.first_name,u.last_name FROM accounts a JOIN account_types at ON at.id=a.account_type_id JOIN users u ON u.id=a.user_id WHERE a.status="active" ORDER BY u.first_name,u.last_name,a.id')->fetchAll();
?><?php $pageTitle=t('Account Funding'); $adminCurrent='funding'; require __DIR__ . '/partials/header.php'; ?><main class="container py-5" style="max-width:900px"><div class="mb-4"><h2 class="fw-bold"><?=e(t('Account Funding'))?></h2><p class="text-muted"><?=e(t('Every funding operation writes a completed ledger entry and recalculates the account balance from the ledger.'))?></p></div><?php if($message):?><div class="alert alert-success"><?=e($message)?></div><?php endif;?><?php if($error):?><div class="alert alert-danger"><?=e($error)?></div><?php endif;?><div class="card border-0 shadow-sm"><div class="card-body p-4"><form method="post"><?=csrf_field()?><div class="row g-3"><div class="col-12"><label class="form-label"><?=e(t('Account'))?></label><select name="account_id" class="form-select" required><option value=""><?=e(t('Select account'))?></option><?php foreach($accounts as $a):?><option value="<?=e((string)$a['id'])?>"><?=e($a['first_name'].' '.$a['last_name'])?> · <?=e($a['type'])?> · <?=e($a['account_number'])?> · <?=e($a['currency'])?> <?=number_format((float)$a['available_balance'],2)?></option><?php endforeach;?></select></div><div class="col-md-6"><label class="form-label"><?=e(t('Operation'))?></label><select name="type" class="form-select" required><option value="opening_balance"><?=e(t('Opening balance (once per account)'))?></option><option value="deposit"><?=e(t('Account funding'))?></option></select></div><div class="col-md-6"><label class="form-label"><?=e(t('Amount'))?></label><div class="input-group"><span class="input-group-text">$</span><input name="amount" class="form-control" inputmode="decimal" min="0.01" required></div></div><div class="col-12"><label class="form-label"><?=e(t('Description'))?></label><input name="description" class="form-control" maxlength="255" value="<?=e(t('Account funding'))?>"></div><div class="col-12"><div class="alert alert-info small mb-0"><?=e(t('Opening balance can only be created once. Additional funds should use account funding. Both operations create completed credit ledger entries and recalculate the account balance from the ledger.'))?></div></div><div class="col-12"><button class="btn btn-primary"><?=e(t('Apply funding'))?></button></div></div></form></div></div></main>
<?php require __DIR__ . '/partials/footer.php'; ?>
