<?php
require_once dirname(__DIR__,2) . '/app/helpers.php';
require_role('admin');
$pdo=Database::connection();
$customers=(int)$pdo->query("SELECT COUNT(*) FROM users WHERE role_id=(SELECT id FROM roles WHERE name='customer')")->fetchColumn();
$accounts=(int)$pdo->query('SELECT COUNT(*) FROM accounts')->fetchColumn();
$balance=(float)$pdo->query('SELECT COALESCE(SUM(available_balance),0) FROM accounts')->fetchColumn();
$transactions=(int)$pdo->query('SELECT COUNT(*) FROM transactions')->fetchColumn();
$user=auth_user();
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Admin - <?=e(APP_NAME)?></title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css" rel="stylesheet"><link href="/commserve/public/assets/css/app.css" rel="stylesheet"></head><body><nav class="navbar bg-dark navbar-dark"><div class="container-fluid"><span class="navbar-brand fw-bold">CommServe Admin</span><span class="text-white small">Signed in as <?=e($user['name'])?></span></div></nav><div class="container-fluid"><div class="row"><aside class="col-lg-2 sidebar p-3"><a class="nav-link active" href="/commserve/public/admin/"><i class="bi bi-speedometer2 me-2"></i>Overview</a><a class="nav-link" href="#"><i class="bi bi-people me-2"></i>Customers</a><a class="nav-link" href="#"><i class="bi bi-wallet me-2"></i>Accounts</a><a class="nav-link" href="#"><i class="bi bi-arrow-left-right me-2"></i>Transactions</a><a class="nav-link" href="/commserve/public/admin/simulate.php"><i class="bi bi-cpu me-2"></i>Simulation</a><a class="nav-link" href="#"><i class="bi bi-person-check me-2"></i>KYC</a><a class="nav-link" href="#"><i class="bi bi-shield-check me-2"></i>Audit Logs</a></aside><main class="col-lg-10 p-4"><div class="alert alert-warning border-0"><b>Simulation Control:</b> All balances and transactions are fictional.</div><h2 class="fw-bold">Operations Dashboard</h2><div class="row g-3 mt-1"><div class="col-sm-6 col-xl-3"><div class="stat-card"><div class="text-muted">Customers</div><div class="fs-2 fw-bold"><?=$customers?></div></div></div><div class="col-sm-6 col-xl-3"><div class="stat-card"><div class="text-muted">Accounts</div><div class="fs-2 fw-bold"><?=$accounts?></div></div></div><div class="col-sm-6 col-xl-3"><div class="stat-card"><div class="text-muted">Simulated Balance</div><div class="fs-4 fw-bold">₦<?=number_format($balance,2)?></div></div></div><div class="col-sm-6 col-xl-3"><div class="stat-card"><div class="text-muted">Transactions</div><div class="fs-2 fw-bold"><?=$transactions?></div></div></div></div><div class="card border-0 shadow-sm mt-4"><div class="card-body"><div class="d-flex justify-content-between align-items-center"><div><h5>Simulation Control Center</h5><p class="text-muted mb-0">Create deposits and withdrawals for testing the banking ledger.</p></div><a class="btn btn-primary" href="/commserve/public/admin/simulate.php">Open simulator</a></div></div></div></main></div></div></body></html>
